"""empty message

Revision ID: 684897aa72d1
Revises: 9016a3022506
Create Date: 2023-05-26 18:29:53.282678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684897aa72d1'
down_revision = '9016a3022506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_starship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_starship')
    # ### end Alembic commands ###
