"""empty message

Revision ID: 810cf75c7cdb
Revises: e8becc46b471
Create Date: 2023-05-31 03:37:09.891015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810cf75c7cdb'
down_revision = 'e8becc46b471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('MGLT', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('url', sa.String(length=250), nullable=False))
        batch_op.create_unique_constraint(None, ['cost_in_credits'])
        batch_op.drop_column('mglt')
        batch_op.drop_column('pilots')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pilots', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('mglt', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('url')
        batch_op.drop_column('MGLT')

    # ### end Alembic commands ###
